### ISSUE TITLE
Your Zcash install guide does not work please delete or fix, no /src reference

### ISSUE THREAD

**Issue by kidputer** [Austin-Williams/zcash-guides#10]
If you are going to go through all the trouble of creating a guide please make sure it works.  There is no /src directory created in your directions that satisfies in the path specified by the binary when it executes so it does not execute.

Please delete or fix and quit wasting people's time.

**Comment by Austin-Williams** [comment]
Huh. That's weird. All the code is gone. It's as if the repository never had any commits. There is no commit history at all. Yet the repos still has 60 stars.

What in that actual....?

**Comment by Austin-Williams** [comment]
@kidputer This worked well back when it was relevant. Less than one week after launch the mining difficulty got high enough that mining on AWS wasn't profitable anymore. At that point this guide became obsolete and stop maintaining it.

It was mostly for testing before launch.

For mining zcash now, I'd look into some of the open source GPU miners available, and I'd pool mine with GPUs. That'll require a much different setup than this guide would have offered.

I'll either delete this repository or else clearly mark it as deprecated.

Thank you for bringing my attention to this.
