### ISSUE TITLE
So the issue is the guide and your directory you type the commands in is not the same

### ISSUE THREAD

**Issue by kidputer** [Austin-Williams/zcash-guides#11]
When you made the guide you changed directories up a path then typed another command but the directions do not reflect this transition so the stuff is built in zcash/zcash/ but referenced in /zcash
I gave up on the maze of directories created and I could not get it to execute.

**Comment by Austin-Williams** [comment]
Stranger than that... I'm seeing the repo as being empty. No files, no commit history. Nothing.

hmmmmm....

**Comment by Austin-Williams** [comment]
Thank you for bringing this to my attention. The guides are outdated. Sorry for the inconvenience. 

I've marked the guides as being deprecated to prevent any others from following them.
