### ISSUE TITLE
Perhaps add a mention of -genproclimit=<n>

### ISSUE THREAD

**Issue by sseefried** [Austin-Williams/zcash-guides#3]
Hi Austin, thank you very much for writing this guide. It helped a lot. I noticed that you did not mention using the `-genproclimit=<n>` flag which allows you to specify the number of processes running. Many of the EC2 instances have multiple cores. I don't understand the Equihash algorithm well enough to say whether throwing more cores at the problem would help, but it seems plausible. Your thoughts?

**Comment by Austin-Williams** [comment]
AFIACT more cores (on the same motherboard) solving equihash concurrently
actually *increases* the EH solve-time. This is because the memory
*bandwidth* is the bottleneck.

**Comment by sseefried** [comment]
I've done some experiments and it seems like you are right, but then why is 100% of the core (that I do use) used if the bottleneck is memory bandwidth? Usually when you have a bottleneck then some other part of the system is under-utilised.

**Comment by sseefried** [comment]
Also, I have another question. You mentioned randomising the nonce for each of the miners. Does this happen automatically? I noticed this issue supposedly was fixed: https://github.com/zcash/zcash/commit/8e165d57d9dec4f5d27478de7a862172264f664e

**Comment by Austin-Williams** [comment]
Yes, that was fixed in one of the alpha releases.

**Comment by Austin-Williams** [comment]
That is a very good question. I don't know the answer. You may want to ask
this one in the forums.

As an aside, have you read the Equihash paper? They discuss what parts of
the algorithm can be parallelize dabs what parts cannot. That may shed some
light.

I hope to learn more about this if/when folks start working on a GPU
implementation.
